### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by chethanyadav456** [GizmolabAI/djs-games#17]
```js
TypeError: Cannot read property 'message' of undefined
    at new ConnectFour (C:\Users\freef\Desktop\Raaz\ApexV2\node_modules\djs-games\games\connect4-game.js:6:22)
    at Object.<anonymous> (C:\Users\freef\Desktop\Raaz\ApexV2\src\commands\Games\connectfour.js:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at C:\Users\freef\Desktop\Raaz\ApexV2\src\structures\ApexClient.js:115:25
    at Array.forEach (<anonymous>)
    at new ApexBot (C:\Users\freef\Desktop\Raaz\ApexV2\src\structures\ApexClient.js:112:34)
    at Object.<anonymous> (C:\Users\freef\Desktop\Raaz\ApexV2\src\apex.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)```

**Comment by chethanyadav456** [comment]
it error on package not on command.

**Comment by gizmo-dev** [comment]
could you share your implementation of code with the package
